export const FATAl_ERROR = "FATAl_ERROR";
export const ERROR = "ERROR";

export const SOCKET_CONNECTED = "SOCKET_CONNECTED";
export const SOCKET_DISCONNECTED = "SOCKET_DISCONNECTED";

export const CHECK_USER = "CHECK_USER";
export const ASK_FOR_USERNAME = "ASK_FOR_USERNAME";

//group action
export const SET_CURRENT_GROUP = "SET_CURRENT_GROUP";
export const CREATE_NEW_GROUP = "CREATE_NEW_GROUP";
export const SERVER_SEND_GROUPS = "SERVER_SEND_GROUPS";
export const SERVER_SEND_GROUP = "SERVER_SEND_GROUP";
export const SERVER_ADD_GROUP = "SERVER_ADD_GROUP";
export const SERVER_REMOVE_GROUP = "SERVER_REMOVE_GROUP";
export const SERVER_UPDATE_GROUP = "SERVER_UPDATE_GROUP";
export const SERVER_ADD_USER_TO_GROUP = "SERVER_ADD_USER_TO_GROUP";
export const SERVER_REMOVE_USER_FROM_GROUP = "SERVER_REMOVE_USER_FROM_GROUP";

//action in socket.io
export const UPDATE_USERS = "UPDATE_USERS";
export const UPDATE_USER = "UPDATE_USER";
export const ADD_USER = "ADD_USER";
export const ADD_USER_RESPONSE = "ADD_USER_RESPONSE";
export const USER_CONNECTED = "USER_CONNECTED";
export const USER_DISCONNECTED = "USER_DISCONNECTED";
export const AUTHENTICATION_BY_PUBLIC_KEY = "AUTHENTICATION_BY_PUBLIC_KEY";
export const UPDATE_CURRENT_USER = "UPDATE_CURRENT_USER";

//messages
export const RECEIVE_MESSAGE = "RECEIVE_MESSAGE";
export const SEND_MESSAGE = "SEND_MESSAGE";
